# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  looplex@v1:
    root: openapi.yaml
extends:
  - recommended
rules:
  no-unused-components: warn
features.openapi:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#336699"