# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  looplex_graph@v1:
    root: openapi.yaml
    # root: openapi/cases.yaml
extends:
  - recommended
rules:
  no-unused-components: warn
features.openapi:
  theme: 
    colors:
      primary:
        main: "#336699"
  htmlTemplate: ./docs/index.html
