# See https://redoc.ly/docs/cli/configuration/ for more information.

# Documentações para configuração
# https://redocly.com/docs/api-reference-docs/configuration/functionality/#example-redocly-configuration-file
apis: 
  looplex_graph:
    root: openapi/openapi.yaml
    rules:
      no-ambiguous-paths: error
rules: 
  no-unused-components: warn
extends: 
  - recommended
features.openapi: 
  expandDefaultServerVariables: true
  htmlTemplate: ./docs/index.html
  theme: 
    colors: 
      primary: 
        main: "#336699"
