title: DTOInterestsConfig
type: object
properties:
  rate:
    description: "Taxa de juros em porcentagem<br />`Required`<br />"
    type: number
  IsProRata: 
    description: "Indica se o Juros é pro rata<br />`Required`<br />"
    type: boolean
  frequency:
    description: "Indica se o juros é  mensal ou anual<br />3 = Mensal<br />4 = Anual <br />`Required`<br />"
    type: integer
    example: 3
  capitalization:
    description: "Indica se os juros são simples (1) ou compostos (2)<br />`Required`<br />"
    type: integer
    example: 1
  startDate:
    description: "Ínicio da vigência"
    example: "2021-05-03T12:00:00-03:00"
    type: string
  startDateEvent:
    description: "Indica a partir de qual evento a data de início será definida<br />0 - Data específica(startDate)<br />1 - Data de Distribuição<br />2 - Data de Citação<br />`Required`<br />"
    type: integer
  startDateAfterNumber:
    description: "Indica a quantidade de dias, meses ou anos após o evento em q será definida a data inicial da vigência"
    example: "2"
    type: integer
  startDateAfterUnit:
    description: "Unidade (dias, mes ou ano) utilizada para definir a data inicial da vigência a partir de um evento<br />0 - Dias<br /> 1 - Meses<br /> 2 - Anos"
    type: integer
  finalDate:
    description: "Data final da vigência "
    example: "2021-05-03T12:00:00-03:00"
    type: string
  finalDateEvent:
    description: "Indicador do Evento a partir do qual será definida a data final da vigência<br />0 - Data específica(finalDate)<br />1 - Data de Distribuição<br />2 - Data de Citação<br />"
    example: "2"
    type: integer
  finalDateAfterNumber:
    description: "Número de dias meses ou anos após o evento a partir do qual será definida a data final da vigência"
    example: "2"
    type: integer
  finalDateAfterUnit:
    description: "Unidade (dias, mes ou ano) utilizada para definir a data final da vigência a partir de um evento<br />0 - Dias<br /> 1 - Meses<br /> 2 - Anos"
    example: "2"
    type: integer
required:
  - rate
  - IsProRata
  - capitalization
  - frequency