title: DTORequestConfig
type: object
properties:
  requestId:
    description: "IdPedidoCausa<br />`Required`<br /> "
    type: integer
  requestName: 
    description: "Nome do Pedido<br />`Required`<br />"
    type: string
  templateId:
    description: "Identificador do template utilizado"
    type: integer
    example: 3
  templateName:
    description: "Nome do template utilizado"
    type: string
  startDate:
    description: "Ínicio do cálculo para o pedido"
    example: "2021-05-03T12:00:00-03:00"
    type: string
  startDateEvent:
    description: "Indica a partir de qual evento a data de início será definida<br />0 - Data específica(startDate)<br />1 - Data de Distribuição<br />2 - Data de Citação<br />`Required`<br />"
    type: integer
  startDateAfterNumber:
    description: "Indica a quantidade de dias, meses ou anos após o evento em q será definida a data inicial da vigência"
    example: "2"
    type: integer
  startDateAfterUnit:
    description: "Unidade (dias, mes ou ano) utilizada para definir a data inicial da vigência a partir de um evento<br />0 - Dias<br /> 1 - Meses<br /> 2 - Anos"
    type: integer
  finalDate:
    description: "Data final do cálculo"
    example: "2021-05-03T12:00:00-03:00"
    type: string
  finalDateEvent:
    description: "Indicador do Evento a partir do qual será definida a data final da vigência<br />0 - Data específica(finalDate)<br />1 - Data de Distribuição<br />2 - Data de Citação<br />"
    example: "2"
    type: integer
  finalDateAfterNumber:
    description: "Número de dias meses ou anos após o evento a partir do qual será definida a data final da vigência"
    example: "2"
    type: integer
  finalDateAfterUnit:
    description: "Unidade (dias, mes ou ano) utilizada para definir a data final da vigência a partir de um evento<br />0 - Dias<br /> 1 - Meses<br /> 2 - Anos"
    example: "2"
    type: integer
  contingency:
    description: "Indica o percentual de contingência para cada risco"
    type: array
    items:
      $ref: DTOContingencyConfig.yaml
  indexRuleList:
    description: "Lista de configurações de correção monetária"
    type: array
    items: 
      $ref: DTOIndexConfig.yaml
  compensatoryInterestList:
    description: "Lista de Configurações de Juros compensatórios"
    type: array
    items: 
      $ref: DTOInterestsConfig.yaml
  defaultInterestList:
    description: "Lista de Configurações de Juros moratórios"
    type: array
    items: 
      $ref: DTOInterestsConfig.yaml
  rebateList:
    description: "Lista de Configurações de Abatimentos"
    type: array
    items: 
      $ref: DTORebateConfig.yaml
  fineList:
    description: "Lista de Configurações de Multas"
    type: array
    items: 
      $ref: DTOPenaltyConfig.yaml
  defaultInterestOverCompensatoryInterest:
    type: boolean
    description: "Indica se os juros moratórios são aplicados sobre os juros compensatórios" 
  updateDate:
    type: string
    description: data da última alteração dessas configurações
    
required:
  - rate
  - IsProRata
  - capitalization
  - frequency