openapi: 3.0.2
info:
  version: 1.0.0
  title: openapi.looplex.com.br
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "/assets/images/logo.png"
    href: "/"
  description: >
    This is an **example** API to demonstrate features of OpenAPI specification

    # Introduction

    This API definition is intended to to be a good starting point for
    describing your API in 

    [OpenAPI/Swagger
    format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md).

    It also demonstrates features of
    [create-openapi-repo](https://github.com/Redocly/create-openapi-repo) tool
    and 

    [Redoc](https://github.com/Redocly/Redoc) documentation engine. So beyond
    the standard OpenAPI syntax we use a few 

    [vendor
    extensions](https://github.com/Redocly/Redoc/blob/master/docs/redoc-vendor-extensions.md).


    # OpenAPI Specification

    The goal of The OpenAPI Specification is to define a standard,
    language-agnostic interface to REST APIs which

    allows both humans and computers to discover and understand the capabilities
    of the service without access to source

    code, documentation, or through network traffic inspection. When properly
    defined via OpenAPI, a consumer can 

    understand and interact with the remote service with a minimal amount of
    implementation logic. Similar to what

    interfaces have done for lower-level programming, OpenAPI removes the
    guesswork in calling the service.
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: "https://github.com/Rebilly/generator-openapi-repo"
tags:
  - name: Document Assembler
    description: Document assembler operations
  - name: Documents
    description: Documents operations
  - name: Template
    description: Template operations
  - name: User
    description: User operations, such as login and profile consulting
  - name: Login (Lawsoft)
    description: Endpoints de login
x-tagGroups:
  - name: Endpoints
    tags:
      - Document Assembler
      - Documents
      - Template
      - User
      - Agenda (Lawsoft)
      - Andamento (Lawsoft)
      - Area (Lawsoft)
      - Busca (Lawsoft)
      - Casos (Lawsoft)
      - Categoria (Lawsoft) 
      - Cliente (Lawsoft)
      - Conta de acesso (Lawsoft)
      - Contato (Lawsoft)
      - Contrato (Lawsoft)
      - Dados complementares (Lawsoft)
      - Decisões (Lawsoft)
      - Despesas (Lawsoft)
      - Expectativa reivindicação (Lawsoft)
      - Fase caso (Lawsoft)
      - Funcionário (Lawsoft)
      - Garantia (Lawsoft)
      - Hierarquia (Lawsoft)
      - Natureza (Lawsoft)
      - Partes (Lawsoft)
      - Pedidos (Lawsoft)
      - Permissão (Lawsoft)
      - Produtos (Lawsoft)
      - Push (Lawsoft)
      - Render (Lawsoft)
      - Session (Lawsoft)
      - Tabela preço categoria (Lawsoft)
      - Tabela preço (Lawsoft)
      - Tarefa (Lawsoft)
      - Timeline (Lawsoft)
      - Timesheet (Lawsoft)
      - Valores apurados (Lawsoft)

servers:
  - url: "http://example.com/api/v1"
    description: Default server
  - url: "https://example.com/api/v1"
  - url: "https://www.sys.lawoffice.com.br/"
paths:
  "/public/docassembler/account/{accountId}/document/{docId}/answers":
    get:
      $ref: ./paths/public@docassembler@account@{accountId}@document@{docId}@answers-get.yaml
  "/public/docassembler/account/{accountId}/document/{docId}/export":
    get:
      $ref: ./paths/public@docassembler@account@{accountId}@document@{docId}@export-get.yaml
  "/public/docassembler/account/{accountId}/document/{docId}/import":
    post:
      $ref: ./paths/public@docassembler@account@{accountId}@document@{docId}@import-post.yaml
  "/public/docassembler/account/{accountId}/document/{docId}/json":
    post:
      $ref: ./paths/public@docassembler@account@{accountId}@document@{docId}@json-post.yaml
  "/public/docassembler/account/{accountId}/document/{docId}/revision-all-answers":
    get:
      $ref: ./paths/public@docassembler@account@{accountId}@document@{docId}@revision-all-answers-get.yaml
  "/public/docassembler/account/{accountId}/template/{template}/persistent":
    post:
      $ref: ./paths/public@docassembler@account@{accountId}@template@{template}@persistent-post.yaml
  "/public/docassembler/account/{accountId}/template/{template}/transient":
    post:
      $ref: ./paths/public@docassembler@account@{accountId}@template@{template}@transient-post.yaml
  "/public/account/{accountId}/document":
    post:
      $ref: ./paths/public@account@{accountId}@document-post.yaml
    patch:
      $ref: ./paths/public@account@{accountId}@document-patch.yaml
  "/public/account/{accountId}/document/hide":
    post:
      $ref: ./paths/public@account@{accountId}@document@hide-post.yaml
  "/public/account/{accountId}/document/unhide":
    post:
      $ref: ./paths/public@account@{accountId}@document@unhide-post.yaml
  "/public/account/{accountId}/document/template/{templateIdentifier}":
    get:
      $ref: ./paths/public@account@{accountId}@document@template@{templateIdentifier}-get.yaml
  "/public/account/{accountId}/document/{docId}":
    get:
      $ref: ./paths/public@account@{accountId}@document@{docId}-get.yaml
    delete:
      $ref: ./paths/public@account@{accountId}@document@{docId}-delete.yaml
  "/public/account/{accountId}/document/{docId}/rem":
    delete:
      $ref: ./paths/public@account@{accountId}@document@{docId}@rem-delete.yaml
  "/public/account/{accountId}/document/{docId}/s3":
    delete:
      $ref: ./paths/public@account@{accountId}@document@{docId}@s3-delete.yaml
  "/public/account/{accountId}/template":
    get:
      $ref: ./paths/public@account@{accountId}@template-get.yaml
  "/public/account/{accountId}/template/{templateId}":
    get:
      $ref: ./paths/public@account@{accountId}@template@{templateId}-get.yaml
  /public/user/login:
    post:
      $ref: ./paths/public@user@login-post.yaml
  
  # Session
  "/api/mobilesession":
    post:
      $ref: ./paths/lawsoft/session/public@api@mobilesession-post.yaml
  "/api/session":
    post:
      $ref: ./paths/lawsoft/session/public@api@session-post.yaml
  "/api/logoff":
    delete:
      $ref: ./paths/lawsoft/session/public@api@logoff-delete.yaml
  
  # Agenda
  "/api/agenda/totaleventos":
    get:
      $ref: ./paths/lawsoft/agenda/public@api@agenda@totaleventos-get.yaml
  "/api/agenda/proximoslancamentos":
    get:
      $ref: ./paths/lawsoft/agenda/public@api@agenda@proximos-lancamentos-get.yaml
  "/api/agenda":
    get:
      $ref: ./paths/lawsoft/agenda/public@api@agenda-get.yaml
  "/api/agenda/remover1":
    post:
      $ref: ./paths/lawsoft/agenda/public@api@agenda@post-post.yaml
  "/api/agenda/remover2":
    put:
      $ref: ./paths/lawsoft/agenda/public@api@agenda@put-put.yaml
  "/api/casos/{idCaso}/agenda":
    get:
      $ref: ./paths/lawsoft/agenda/public@api@casos@{idCaso}@agenda-get.yaml
  "/api/agenda/{tipo}/{id}":
    delete:
      $ref: ./paths/lawsoft/agenda/public@api@agenda@{tipo}@{id}-delete.yaml
  "/api/agenda/executores":
    get:
      $ref: ./paths/lawsoft/agenda/public@api@agenda@executores-get.yaml
  "/api/agenda/participantes":
    get:
      $ref: ./paths/lawsoft/agenda/public@api@agenda@participantes-get.yaml
  "/api/agenda/titulos":
    get:
      $ref: ./paths/lawsoft/agenda/public@api@agenda@titulos-get.yaml
  "/api/casos/{idCaso}/audiencias":
    get:
      $ref: ./paths/lawsoft/agenda/public@api@casos@{idCaso}@audiencias-get.yaml
  "/api/casos/num/audiencias":
    get:
      $ref: ./paths/lawsoft/agenda/public@api@casos@num@audiencias-get.yaml
  "/api/casos/{idCaso}/tabagenda":
    get: 
      $ref: ./paths/lawsoft/agenda/public@api@casos@{idCaso}@tabagenda-get.yaml
  "/api/casos/num/tabagenda":
    get:
      $ref: ./paths/lawsoft/agenda/public@api@casos@num@tabagenda-get.yaml
  
  # Andamentos
  "/api/andamentos/templates":
    get:
      $ref: ./paths/lawsoft/andamento/public@api@andamentos@templates-get.yaml

  #Timeline
  "/api/timeline/items":
    get:
      $ref: ./paths/lawsoft/timeline/public@api@timeline@items-get.yaml

  # Produtos
  "/api/casos/{idCaso}/produtos":
    get:
      $ref: ./paths/lawsoft/produtos/public@api@casos@{idCaso}@produtos-get.yaml
  "/api/casos/num/produtos":
    get:
      $ref: ./paths/lawsoft/produtos/public@api@casos@num@produtos-get.yaml

  # Permissão
  "/api/permissao/{idFuncionalidade}":
    get:
      $ref: ./paths/lawsoft/permissao/public@api@permissao@{idFuncionalidade}-get.yaml

  # Fase
  "/api/casos/fase/{nrGrupo}":
    get:
      $ref: ./paths/lawsoft/fase_caso/public@api@casos@fase@{nrGrupo}-get.yaml
  "/api/casos/{nrSequencia}/fase":
    get:
      $ref: ./paths/lawsoft/fase_caso/public@api@casos@{nrSequencia}@fase-get.yaml
  "/api/casos/num/fase":
    get:
      $ref: ./paths/lawsoft/fase_caso/public@api@casos@num@fase-get.yaml

  # Dados complementares
  "/api/casos/{idCaso}/dadoscomplementares":
    get:
      $ref: ./paths/lawsoft/dados_complementares/public@api@casos@{idCaso}@dadoscomplementares-get.yaml
  "/api/casos/num/dadoscomplementares":
    get:
      $ref: ./paths/lawsoft/dados_complementares/public@api@casos@num@dadoscomplementares-get.yaml

components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "http://example.com/api/oauth/dialog"
          scopes:
            "read:users": read users info
            "write:users": modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    auth_token:
      type: apiKey
      in: header
      name: auth_token
    basic_auth:
      type: http
      scheme: basic
