
openapi: 3.0.2
info:
  version: 1.0.0
  title: Tasks
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "/assets/images/logo.png"
    href: "/"
  description: >
    # Graph
    
    Looplex Graph é grupo de APIs consumidas pela interface web Looplex, relacionadas aos fluxos de documentos, templates e tarefas.


    # Começando

    ...
servers:
  - url: "https://graph.looplex.com/api/v1/tasks"
    description: Graph server
tags:
  - name: Tasks
    description: Tasks operations
paths:
  /tasks:
    get:
      $ref: ./paths/tasks-api/tasks-get.yaml
    post:
      $ref: ./paths/tasks-api/tasks-post.yaml
  /tasks/me:
    get:
      $ref: ./paths/tasks-api/tasks@me-get.yaml
  /tasks/{taskId}:
    patch:
      $ref: ./paths/tasks-api/tasks@{taskId}-patch.yaml
    get:
      $ref: ./paths/tasks-api/tasks@{taskId}-get.yaml
    delete:
      $ref: ./paths/tasks-api/tasks@{taskId}-delete.yaml
    put:
      $ref: ./paths/tasks-api/tasks@{taskId}-put.yaml
components:
  securitySchemes:
    Subscription-Key:
      $ref: ./components/securitySchemes/ocp_apim_subscription_key.yaml
security:
  -  Subscription-Key: []
    
  
