# https://redocly.com/docs/openapi-visual-reference/info/
openapi: 3.0.2
security: 
  - Ocp-Apim-Subscription-Key: []
info:
  version: 1.0.0
  title: "API interna de planilha padrão"
  termsOfService: "https://docs.looplex.com.br/legal/termos-de-uso"
  contact:
    name: Developers Looplex
    email: developer@looplex.com.br
    url: "https://www.looplex.com.br"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://www.looplex.com.br/img/logo-default.png"
    href: "/"
  description: >
    Documentação de planilha padrão
servers:
  - url: "https://planilhapadrao.lawoffice.com.br"
    description: "Gerador de arquivo mdb de planilha padrão"
paths:
  /api/generate_mdb_file:
    post:
      $ref: './paths/planilha_padrao/public@api@generate_mdb_file-post.yaml'
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
    Ocp-Apim-Subscription-Key:
      type: apiKey
      in: header
      description: "Subscription key provided by Looplex"
      name: Ocp-Apim-Subscription-Key
    auth_token:
      type: apiKey
      in: header
      name: auth_token
    basic_auth:
      type: http
      scheme: basic